baseURL = "https://jesuisdidi.neocities.org/"
languageCode = "en-us"
theme = "glim-midnight"

[params]
    headtitle = "Je Suis Didi"
    title = "Didi Di Cesare"
    socialLinks = [
        {name = "Mastodon", url="https://mastodon.online/@didierofrivia", icon="mastodon.svg"},
    ]
    avatar = "dd-avatar-01.jpeg"
    about = "A mostly nice human being, attempting to create, while this late age of surveillance capitalism wants to enslave us into consumerism."
    streamingLinks = [
        {name = "Tidal", url = "https://tidal.com/browse/album/394014794"},
        {name = "Spotify", url = "https://open.spotify.com/track/7zCxTXk6yjWj6n0M0ZlvHB?si=8dc36c768a9146ed"},
        {name = "Deezer", url = "https://deezer.page.link/MRbGCrPwveQYFdMY9"},
        {name = "Apple Music", url = "https://music.apple.com/us/album/the-plot-single/1774559721"},
        {name = "YouTube Music", url = "https://music.youtube.com/playlist?list=OLAK5uy_lpSAyGpDFBaKmM5XZok-5IyLG2vVySxfY"},
    ]
    background = "bg.mp4"