baseURL = "https://jesuisdidi.neocities.org/"
languageCode = "en-us"
theme = "glim-midnight"

[params]
    headtitle = "Je Suis Didi"
    title = "Didi Di Cesare"
    socialLinks = [
        {name = "Mastodon", url="https://mastodon.online/@didierofrivia", icon="mastodon.svg"},
    ]
    avatar = "dd-avatar-01.jpeg"
    about = "A mostly nice human being, attempting to create, in this late age of surveillance capitalism."
    streamingLinks = [
        {name = "Tidal", url = "https://tidal.com/browse/artist/51199476"},
        {name = "Spotify", url = "https://open.spotify.com/artist/1N8ts2Tb3LHeXFtlw0Bi3y"},
        {name = "Deezer", url = "https://www.deezer.com/en/artist/286543721"},
        {name = "Apple Music", url = "https://music.apple.com/us/artist/didi-di-cesare/1774558919"},
        {name = "YouTube Music", url = "https://music.youtube.com/channel/UCZ5jWAYZ2AqNV02ZPooPwfQ"},
    ]
    background = "bg.mp4"
